// Generated by CoffeeScript 1.7.1
var express, http, router;

express = require('express');

http = require('http');

router = express.Router();

router.get('/', function(req, res) {
  var options, reqPost;
  options = {
    host: 'analytics23.server.163.org',
    port: 8888,
    path: '/api/lesson-rank/?date=2014-05-11&comparedate=2014-05-10&limit=0,10',
    method: 'GET'
  };
  reqPost = http.request(options, function(resPost) {
    var resData;
    resData = '';
    resPost.on('data', function(chunk) {
      return resData += chunk;
    });
    return resPost.on('end', function() {
      return res.render('index', {
        title: 'Express',
        data: JSON.parse(resData)
      });
    });
  });
  reqPost.end();
  return reqPost.on('error', function(e) {
    return console.error(e);
  });
});

module.exports = router;
